---
development:
  cloud_name: jorgecarabali
  api_key: '312564415435813'
  api_secret: 3E8-10vYowzVOLy83-rVYr74dBo
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: jorgecarabali
  api_key: '312564415435813'
  api_secret: 3E8-10vYowzVOLy83-rVYr74dBo
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: jorgecarabali
  api_key: '312564415435813'
  api_secret: 3E8-10vYowzVOLy83-rVYr74dBo
  enhance_image_tag: true
  static_file_support: false
